### ISSUE TITLE
任务详情编辑 markdown 不支持快捷键

### ISSUE THREAD

**Issue by SimplyY** [origingroup/hydrogen#1]
推荐 bear，bear 的写 markdown 使用快捷键的体验不错

**Comment by SimplyY** [comment]
支付宝里转账备注， qq、扣扣等都是敏感词= =，邮箱没法填，而且备注有长度限制

**Comment by 6174** [comment]
是的，现在发现这个问题了，所以页面上加上了通过 email 带支付信息给， 这个应该要高亮一下，后面还是得做自动支付，接入 fast-spring 是个选择，不过发现每笔要 .75$的费用，得亏死！

**Comment by 6174** [comment]
bear 貌似不错，我先看看有哪些不错的功能可以值得借鉴的，到时候 copy 过来！

**Comment by 6174** [comment]
1.1.7 Bear 的快捷键应该大部分都支持了

**Comment by SimplyY** [comment]
1.17 beta 我这边快捷键没用，是键位不一样吗。

![image](https://user-images.githubusercontent.com/8455579/28108079-d96b7f9c-671c-11e7-912c-f7eb32b926db.png)

![image](https://user-images.githubusercontent.com/8455579/28108086-e1cce068-671c-11e7-852c-888eab7d44e4.png)
