### ISSUE TITLE
编辑事务页面的输入区 UI 指引问题

### ISSUE THREAD

**Issue by isjanuary** [origingroup/hydrogen#10]
### tooltip 问题
想法是不错，但还是最好有一个固定的文字编辑框置顶，不知道其他人想法怎么样

### 列表项问题
事务区内置了类似 MS word 的自动列表功能，1. 2. 3. 4. ...  自动编号这样。问题是一旦列表开始自动编号，无法取消编号操作。比如，已存在如下内容：
```
2. 这里是任意内容
``` 
我编辑完了，希望在 2 下面添加子内容，我敲了回车以后，希望不生成编号 3 ，而让我自由输入。简言之，就是不产生以下效果：
```
2. 这里是任意内容
3.
```
而是这样
 ```
2. 这里是任意内容
    自由编辑
```

还有些功能也是，能开不能关，有点难受。

**Comment by 6174** [comment]
先感谢这么认真的建议回复！

那我这里先说一说新版的编辑器设计吧：

## tooltip 的问题：

设计编辑器这件事情得有一个确定的方向，不然做出来的东西就是永远赶不上 word 的富文本编辑器，而氢设计编辑器的基本原则就是：“用尽量简洁的方式表达用户需要的东西”。所以氢的编辑器目标非 word，而更像 medium ，像 markdown 这种简洁的通过几个特定的 block 元素和 inline 元素就能表达 80% 的编辑需求，这样在编辑效率和编辑专注度上更偏向文字内容，而非 style，只是取了一个折中点，所以不会设计置顶文本编辑框！


同时对应基本样式控制，新版的编辑器用户三种方式

1. shortcuts （markdown + 基本 inline shortcuts）
2. slash tool （用于快速方便的插入块级元素，Format 块级元素）
3. inline toolbar （放在最弱的位置）

先来张 slash tool 的截图
<img width="515" alt="2017-07-01 5 50 45" src="https://user-images.githubusercontent.com/3872872/27755273-451426c2-5e21-11e7-9668-d16aa23cd003.png">


## list 的问题

这个问题在新版的编辑器会得到很好的支持，原先使用的基础 lib 对于你说的这种情况的支持很难，新版完全重构过后可以完美解决，在列表 block 上使用 slash tool 输入 / 选择插入段落，插入图片都可以

<img width="680" alt="2017-07-01 5 54 27" src="https://user-images.githubusercontent.com/3872872/27755358-c7bbfd66-5e21-11e7-8036-453adc7bff72.png">

**Comment by 6174** [comment]
v1.1.9 这类编辑已支持
