### ISSUE TITLE
目前只有一个根目录，是否有进一步的开发计划？

### ISSUE THREAD

**Issue by nechoyan** [origingroup/hydrogen#11]
根目录可以延伸出project的概念。这样不同的project可以有不同的页面来管理所有的子任务。

**Comment by 6174** [comment]
@nechoyan   实际上任何节点都可以作为“根”，点击任务左边的小圆点 pop 后的结果会保存，如果你不 pop 其他的，这个时候这个任务就是根。 

不过这个需求确实还挺多，后面应该会通过 git repo 的模式来支持，可以整体切换 repo，这样应该就可以有多个 project

**Comment by ghost** [comment]
对啊，我也准备过来提这个需求的，刚好看到了。另外，以后能分多个的话，最好有笔记和待办的选择，因为真的我只是单纯写笔记，真的不需要任务看板那块，而且任务看板那块真的占地方

**Comment by 6174** [comment]
v1.1.9  已支持 多个 project
