### ISSUE TITLE
[Feature Request] 是否有计划开发粘贴图片功能？

### ISSUE THREAD

**Issue by oott123** [origingroup/hydrogen#12]
很喜欢 Hydrogen ~
想问有没有计划支持图片功能呢？比如从剪贴板粘贴图片？
觉得这样拿来做笔记的话，会比较好用！
谢谢啦

**Comment by 6174** [comment]
1.1.6 已经支持，包括

1. 拖拽插入图片
2. 复制粘贴图片
3. 粘贴图片url
4. 粘贴 html 图片
5. 输入 /image  选择 add Image 插入图片

**Comment by oott123** [comment]
∑(๑º口º๑)!!原来 1.1.6 在 1.1.5 下面…
习惯性的下载第一个 release 了…
谢谢！

**Comment by 6174** [comment]
我也奇怪为什么 1.1.6 在 1.1.5 后面
