### ISSUE TITLE
代码块中粘贴带换行的代码会新建 block

### ISSUE THREAD

**Issue by oott123** [origingroup/hydrogen#14]
复制以下代码块：

```javascript
var a = "Hello";
var b = "World";
console.log(a + b);
```

去 Hydrogen 中创建一个代码块，然后粘贴：

![default](https://user-images.githubusercontent.com/905663/27902614-f81f3ab8-6268-11e7-9272-e0d321c8e7c3.png)

**Comment by oott123** [comment]
以及不管是手动输入，还是粘贴，我都没法在代码块里插入一个空行。

**Comment by 6174** [comment]
该问题 1.1.7 已解决

**Comment by oott123** [comment]
![](https://user-images.githubusercontent.com/905663/28001322-40eb0f40-655e-11e7-9d44-025329a82c1d.gif)

连续敲击两个回车，还是会到下一个 block 里。这样一来，代码块里插入空行变得困难了。

**Comment by 6174** [comment]
@oott123  这个特意而为，因为在某种情况，code 是最后一个 block， 这样就没法输入其他的信息了，必须得有方法 exit block 才行，现在设定的条件是最后两行为空行，有些设定的条件是 输入 ```换行，但是为了统一我都用了两个空行最后退出条件

如果想输入多行空行，没问题的，因为检查条件是最后两行空行，也就是如果不是最后的空行，之前插入多少个空行都没问题

**Comment by oott123** [comment]
谢谢，我理解了。
