### ISSUE TITLE
[Feature Request] 高亮代码种类支持

### ISSUE THREAD

**Issue by oott123** [origingroup/hydrogen#15]
目前只有 JS/CSS/HTML

能否考虑加入对其它语言的支持？

-----

PS. 一口气提这么多 issue 有点不好意思了……

**Comment by 6174** [comment]
哈哈，🤝，有人提 bug 证明有人在用新版编辑器了，其实代码块的 bug 已经解决了不过还没发，语言支持很容易，然后 / 工具的位置问题估计这周这些问题可以一并解决掉

**Comment by 6174** [comment]
1.1.7 已新增

**Comment by oott123** [comment]
![default](https://user-images.githubusercontent.com/905663/28001504-9c2cbbfa-655f-11e7-9ec2-f4f09a4adc81.png)

不得不说这个高亮什么鬼……哪里不太对吧？

**Comment by 6174** [comment]
你能重新下载最新版本么=。=，应该不是这样的才对

**Comment by 6174** [comment]
正确的应该是这样的呀

<img width="773" alt="2017-07-10 11 08 03" src="https://user-images.githubusercontent.com/3872872/28001558-10cebcc4-6560-11e7-9597-907641fd8d41.png">

**Comment by oott123** [comment]
我下载的 zip 包的 sha1 值如下：

```
$ sha1sum Hydrogen-1.1.7-mac.zip
dd64a4a4f1797b967cc1dbfc70a8e46f915b333d  Hydrogen-1.1.7-mac.zip
```

我把整个 .app 文件夹删了，重新解压再打开，还这样，需要我做其它操作吗……
顺带一提，我这每次打开 app 都有新手引导……是不是同一个问题导致的呢？

**Comment by 6174** [comment]
居然不一致：我重新上传七牛试一下


➜ release git:(feature/nodegit) ✗ sha1sum Hydrogen-1.1.7-mac.zip
afb1f14a1e7f4147ca38eca0afab1f9566c3f0ad Hydrogen-1.1.7-mac.zip


原始邮件
发件人:三三notifications@github.com
收件人:origingroup/hydrogenhydrogen@noreply.github.com
抄送:陈学家 - XUEJIA CHEN570171025@qq.com; State changestate_change@noreply.github.com
发送时间:2017年7月10日(周一) 11:20
主题:Re: [origingroup/hydrogen] [Feature Request] 高亮代码种类支持 (#15)


我下载的 zip 包的 sha1 值如下：
$ sha1sum Hydrogen-1.1.7-mac.zip dd64a4a4f1797b967cc1dbfc70a8e46f915b333d Hydrogen-1.1.7-mac.zip
我把整个 .app 文件夹删了，重新解压再打开，还这样，需要我做其它操作吗……
 顺带一提，我这每次打开 app 都有新手引导……是不是同一个问题导致的呢？
