### ISSUE TITLE
V1.1.5 Beta和V1.1.6 Beta MAC版安装均报错

### ISSUE THREAD

**Issue by kathleensun** [origingroup/hydrogen#16]
安装中，报错，无法安装，见图。

![jietu20170706-191754](https://user-images.githubusercontent.com/29950970/27913768-b32ba40c-6293-11e7-8fd2-5b8b3f303baf.jpg)

**Comment by 6174** [comment]
因为氢是依赖系统的git的，你发的报错应该是 git 执行的错误，

试一下在 terminal 中执行这个再重新打开看看能否解决

```shell
xcode-select --install
```
具体原因见：

http://tips.tutorialhorizon.com/2015/10/01/xcrun-error-invalid-active-developer-path-library-developer-commandline-tools-missing-xcrun/

Have you upgraded to OS X El Cap­i­tan from App Store ?

Have you sud­denly started get­ting the fol­low­ing error in your project?

Remem­ber, in MAC git is attached to XCode’s Com­mand line tools.

基本判断应该是和你电脑系统的升级方式的问题了

**Comment by kathleensun** [comment]
是电脑版本的问题么？

![image](https://user-images.githubusercontent.com/29950970/27914351-6bda07e0-6295-11e7-93e0-e0b65a8be504.png)

**Comment by 6174** [comment]
@kathleensun  并不是电脑版本的问题，是系统升级带来的问题，你打开 terminal.app 执行

```shell
xcode-select --install
```
试一下，看能否解决问题

**Comment by kathleensun** [comment]
运行了该命令，开始下载软件。软件安装后，问题已解决！

**Comment by 6174** [comment]
好，那我把 issue close 了
