### ISSUE TITLE
1.1.6beta版本安装后一打开app就出现问题

### ISSUE THREAD

**Issue by Rogershenyc** [origingroup/hydrogen#17]
出现如下图的问题
![2017-07-06 22 46 30](https://user-images.githubusercontent.com/17106938/27917631-18430672-629f-11e7-94ac-e49162615eee.png)

**Comment by zhoulianglen** [comment]
你的 Git 有问题

**Comment by Rogershenyc** [comment]
恩恩，是的，这个问题已经解决了。

**Comment by 6174** [comment]
问题主要是 git 无法解析本机的邮箱导致，执行提示中的命令重新配置 git  用户名，邮箱就行

打开 terminal.app 

```sh
git config --global user.name "你的名称"
git config --global user.email "你的邮箱"
```
