### ISSUE TITLE
希望能禁用软件中的CMD+R刷新

### ISSUE THREAD

**Issue by chenxtdo** [origingroup/hydrogen#18]
加了 Tags 无法删除

**Comment by chenxtdo** [comment]
git checkout 不实时反映到工作区的

**Comment by 6174** [comment]
@chenxtdo  

1. 禁用 CMD + R 刷新能说一下什么情况会影响体验吗？
2. 输入 tag 估计有 bug 这个尽快解决
3. 目前的版本只是简单集成了 git，候选会做更多的考虑和设计

**Comment by chenxtdo** [comment]
@6174  CMD+R 刷新了 ， 就不在当前页面了

**Comment by 6174** [comment]
1.1.7 已禁止刷新
