### ISSUE TITLE
1.1.0版本关闭后，点击dock栏没法恢复界面，只有退出重新打开

### ISSUE THREAD

**Issue by nibin666** [origingroup/hydrogen#2]
![jietu20170622-173845 2x](https://user-images.githubusercontent.com/15081119/27427654-521a419a-5772-11e7-8b87-c9a49b72b64d.jpg)

此状态下点击菜单-窗口-重新加载（或全屏）会出图中错误。
系统版本 10.12.4

**Comment by 6174** [comment]
问题收到，这周末就修复掉！

**Comment by 6174** [comment]
1.1.1 版本已修复
