### ISSUE TITLE
默认的说明，无法删除问题……

### ISSUE THREAD

**Issue by feichai** [origingroup/hydrogen#21]
试了好多次，似乎就是无法删除的，只能删除了文字，修改为工作用的 inbox。
默认说明似乎是最顶级的，其他任何新建的列表，都 会有一个圈圈，默认的就没有？

**Comment by feichai** [comment]
看了下说明，似乎是因为这是根目录？
那就不应该把说明置顶啊……他也应该属于根目录下属的列表，我弄了好久，才发现这一点。

**Comment by 6174** [comment]
你说的这点建议确实得考虑调整，关于删除这个问题困惑了挺多用户

**Comment by 6174** [comment]
v1.1.9 支持多个项目，可以从这个角度来考虑删除根的问题，根肯定是无法删除的，现在可以切换项目
