### ISSUE TITLE
是否有体验版本？

### ISSUE THREAD

**Issue by nelson-s** [origingroup/hydrogen#25]
理念非常不错，
非常符合自己想要的产品，
不过看到不少评论都讲到产品的一些体验的细节问题，
请问这个是否有体验版本供体验。

**Comment by 6174** [comment]
@nelson-s 直接下载可用，未购买 license 限制能创建至多 100 个节点

**Comment by nelson-s** [comment]
恕我直言。
刚才体验了一下，发现其中还有不少的细节问题需要优化。
当前收费可能操之过急。

发自我的 iPhone

**Comment by 6174** [comment]
@nelson-s  相关体验问题方便的话可以写在 issue 里吗 ，THX

**Comment by nelson-s** [comment]
Hi，
是否有种子用户群呢？一些想法可以在用户群中进行交流。
虽然在github进行沟通也能够沉淀问题，但是我感觉对于产品后续的发展而言，或许不是什么太好的事情。
毕竟初期大家讨论问题比较多的话，是会影响新用户的尝试意愿的。




------------------------------------
宋瑞强 
图灵机器人  平台负责人
北京光年无限科技有限公司
TEL:18510509391
QQ:876128079
Web：www.tuling123.com
