### ISSUE TITLE
关于历史版本与自动保存问题

### ISSUE THREAD

**Issue by tiandaxia11** [origingroup/hydrogen#27]
不知道是如何自动保存的，我经历过两次系统更新自动重启之后之前编辑的内容就没有了，而且在历史版本中也看不到。
另外我的历史版本中只有一条记录是不是不正常呀？
上一个截图
![2017-07-31 10 31 20](https://user-images.githubusercontent.com/30582397/28760705-7becb5de-75db-11e7-9588-44997404aa4d.png)

**Comment by 6174** [comment]
正常逻辑点击版本库右边的 icon，如果有编辑的话应该会弹出保存框，输入过后点击 commit 应该会保存

**Comment by 6174** [comment]
如果没保存过，只有一条记录是正常的

**Comment by tiandaxia11** [comment]
**收到，已经会使用了，感谢！**
