### ISSUE TITLE
使用的markdown都支持哪些语法呀？可以增加删除线么？

### ISSUE THREAD

**Issue by Chen-DaYi** [origingroup/hydrogen#28]
感觉有些markdown的语法不支持呢，比如ToDo，比如删除线。求增加呀

**Comment by 6174** [comment]
1.1.9 已增加 todo ，插入方式为输入 `/todo` 选择插入
删除线语法为 `~~asdf~~ + 空格`， markdown的语法基本都支持呀，在引导里边应该有说才对
