### ISSUE TITLE
初次安装打开提示Error，建议增加登录或者配置

### ISSUE THREAD

**Issue by xiun2005** [origingroup/hydrogen#32]
*** Please tell me who you are. Run git config --global user.email "you@example.com" git config --global user.name "Your Name" to set your account's default identity. Omit --global to set the identity only in this repository. fatal: unable to auto-detect email address (got 'Seven@bogon.(none)')

**Comment by 6174** [comment]
1.1.9  整体替换了 git，使用 内置 git，不会出现这类问题了
