### ISSUE TITLE
写完任务无法点击保存（提交）按钮

### ISSUE THREAD

**Issue by zjplus** [origingroup/hydrogen#33]
软件一段时间后就会出现无法点击保存按钮，同时无法切换版本，退出软件重新打开就行，但是数据会丢失。

发现是个bug，并且100%可重现。在看板里做了移动的修改就不能保存，并且会丢失已久修改的数据

**Comment by zjplus** [comment]
发现有几位已经出现了同样的问题，故此关闭

**Comment by 6174** [comment]
问题 1.1.9 应该已经修复
