### ISSUE TITLE
建议增加新手引导

### ISSUE THREAD

**Issue by jimmywzm** [origingroup/hydrogen#4]
使用了一阵子，发现貌似 Hydrogen 没法新增多个一级待办呀~每次回车都是在一级待办里面，新增一个二级待办。
还是说我没找到？建议在应用的某个角落加个快捷键帮助。

**Comment by 6174** [comment]
使用 tab 快捷键，shift-tab 可以缩进！
可是使用control + command + 上下键上下移动！

目前主要在做编辑器的工作，完成了就会去做新手引导了，还有就是其他的使用文档也得完善起来！

**Comment by wikilike7** [comment]
@6174  我的很奇怪的是tab和shift-tab并不能缩进，版本是最新的

**Comment by 6174** [comment]
@wikilike7 是不是和你自己的键盘设置有关，或者输入法相关，目前还没遇到过这个问题！

**Comment by 6174** [comment]
新手引导功能 V 1.1.4 beta 已加！
