### ISSUE TITLE
还不错，但是操作上还需要进步

### ISSUE THREAD

**Issue by wikilike7** [origingroup/hydrogen#6]
写计划的那种快感还是缺乏了点，期望写的这个步骤的支持更好，比如支持Markdown更多功能和快捷键

**Comment by 6174** [comment]
Markdown 的基本功能应都是支持的，包括，Heading，bold，italic，code block，link，image， list ，blockquote。 对应的快捷键和 markdown 应该是一致。

不过最近的主要工作就是在做编辑器这部分，现在在参考一些其他的编辑器在做，比如 notion 的！
