### ISSUE TITLE
Mac 1.1 存在错误

### ISSUE THREAD

**Issue by songge110** [origingroup/hydrogen#7]
<img width="1100" alt="wx20170627-073128 2x" src="https://user-images.githubusercontent.com/3199081/27564498-b6805638-5b0a-11e7-92d4-7d92fe0d7646.png">
这个问题，应该怎么解决呢？

**Comment by 6174** [comment]
是什么场景出现的这个错误，可以仔细描述一下吗？

**Comment by 6174** [comment]
先临时解决问题的办法：试一下手动到这个仓库位置，修改一下 app.json ，然后 commit 一下，我晚上看看能不能尽快修复掉

**Comment by yanQuanfei** [comment]
我也是遇到了这个问题，就是正常打开，不会有序列号窗口，相关问题我会发到你的邮箱。

**Comment by 6174** [comment]
@songge110 能用终端 cd 到 

`/Users/{你的用户目录}/Library/Application\ Support/hydrogen/hydrogen-repo`

查看一下是否有文件吗? 正确的场景结构应该像下面这样的

```shell
├── app.json
└── tasks
    ├── task-04e3a878-6c5a-46eb-b6c2-a33932638500.json
    ├── task-0575ec92-6c7b-4ee2-bd3f-1690a570bc93.json
```

这个目录是一个 git repo ，如果方便的话，能提供一下 git log 和 git status 就更好了

有劳！

**Comment by Rogershenyc** [comment]
我也是遇到这个问题，打开就显示这个

**Comment by 6174** [comment]
@Rogershenyc 能否按照上面的方法 查看一下是否有相关文件呢？ 万分感谢！

如果没有，能否把这个 hydrogen-repo 整个文件夹删除了，再看看是否能打开！

**Comment by Rogershenyc** [comment]
多亏开发者细心指导，问题已经解决。用terminal.app，cd到
`/Users/{你的用户目录}/Library/Application\ Support/hydrogen/hydrogen-repo/tasks`之后，执行
`git add -A`和`git commit -am"init commit"`
之后重启氢即可。

**Comment by 6174** [comment]
1.1.7 自动解决 commit 未成功的问题，每次进入都会检查是否有初始化 commit， 如果没有那么会新建初始化 commit
