### ISSUE TITLE
左侧 commit 时间用 fromNow 显示

### ISSUE THREAD

**Issue by isjanuary** [origingroup/hydrogen#9]
<img width="211" alt="default" src="https://user-images.githubusercontent.com/20678087/27730498-fd2933d0-5dbb-11e7-9155-01a04f6ca908.png">

左侧显示  commit 时间的部分，不要显示 YYYY-MM-DDTHH:MM:SS+GMT 格式，太生硬了。能否用 moment 包的 fromNow  函数显示成 类似
* A few seconds ago
* M min ago
* D days ago
这样

**Comment by 6174** [comment]
可以的，这部分的功能是赶着做完的，等编辑器功能完善了，再完整优化 git 功能

**Comment by 6174** [comment]
v1.1.9  改为了 fromNow
